server:
  port: 8081

spring:
  application:
    name: cinema-db
  datasource:
    password: willianbdb
    url: jdbc:postgresql://localhost:5432/cinema-db
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

